class APIErr:
    NO_ERROR = dict(code=0, message="成功")
    WRONG_ACCOUNT_PASSWD = dict(code=1, message="账号或密码不正确")
    ACCOUNT_STATUS_DISABLE = dict(code=2, message="账号被停用")
    SUPERADMIN_PROTECT = dict(code=3, message="不能操作超级管理员账号")
    ACCOUNT_EXISTSED = dict(code=4, message="账号已存在")
    PHONE_EXISTED = dict(code=5, message="手机号已存在")
    ROLE_EXISTED = dict(code=6, message="角色已存在")
    ORG_USER_STATUS_DISABLE = dict(code=7, message="组织用户被停用")
    USER_UUID_EXISTED = dict(code=8, message="用户UUID已存在,请重试")
    ORG_UUID_EXISTED = dict(code=9, message="组织UUID已存在,请重试")
    ORG_NAME_EXISTED = dict(code=10, message="组织名称已存在")
    ORG_OWNER_NOT_EXISTED = dict(code=11, message="不存在该用户")
